// version_info.h
#define VERSION_MAJOR 0
#define VERSION_MINOR 6
#define VERSION_REVISION 0
#define VERSION_BUILD 0

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VER_FILE_VERSION \
  VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_BUILD
#define VER_FILE_VERSION_STR \
  STRINGIZE(VERSION_MAJOR) "." STRINGIZE(VERSION_MINOR) "." STRINGIZE(VERSION_REVISION) "." STRINGIZE(VERSION_BUILD)

#define VER_PRODUCTNAME_STR "plugK 刀剑封魔录系列增强补丁"
#define VER_COMPANYNAME_STR "cartman-kai github.com/cartman-kai"
#define VER_COPYRIGHT_STR "Copyright (C) 2025-2026"
