// plugK/src/config.c

#include <stdio.h>
#include <string.h>
#include <stdlib.h> // for _itoa
#include "../inc/config.h"

PK_CONFIG g_pk_config = {0};

// 辅助：检查 Key 是否存在，不存在则写入默认值
static void CheckAndWriteDefault(const char *iniPath, const char *section, const char *key, int defaultVal, const char *desc)
{
    char buf[32];
    // 尝试读取，如果读不到，GetPrivateProfileString 会返回 default 字符串
    // 但这里我们用更直接的方法：直接看能不能读到东西
    GetPrivateProfileStringA(section, key, "MISSING", buf, 32, iniPath);

    if (strcmp(buf, "MISSING") == 0)
    {
        // 没找到该 Key，说明是新功能，写入默认值
        char valStr[16];
        snprintf(valStr, 16, "%d", defaultVal);

        // 写入值
        WritePrivateProfileStringA(section, key, valStr, iniPath);

        // 写入注释 (Win32 API 不支持直接写行内注释，这是个折衷方案)
        // 我们尝试写入一个特殊的 Key "; Comment" 来模拟注释，但在 Section 中位置不确定
        // 或者，由于我们是在补全，用户下次打开就能看到 Key 了。
        // 为了简单，我们只补全 Key=Value。如果想要完美注释，需要用之前的 SafeSave 逻辑重写整个文件。
        // 这里采用方案：只补全 Key=Value，保证功能可用。
    }
}

void pk_config_load(const char *optional_path)
{
    char ini_path[MAX_PATH];

    if (optional_path && strlen(optional_path) > 0)
    {
        strcpy_s(ini_path, MAX_PATH, optional_path);
    }
    else
    {
        char dll_path[MAX_PATH];
        HMODULE hModule = GetModuleHandleA("PlugK.dll");
        if (!hModule)
            hModule = GetModuleHandleA(NULL);
        GetModuleFileNameA(hModule, dll_path, MAX_PATH);
        char *last_slash = strrchr(dll_path, '\\');
        if (last_slash)
            *(last_slash + 1) = '\0';
        snprintf(ini_path, MAX_PATH, "%sPlugK.ini", dll_path);
    }

    // 1. 如果文件完全不存在，创建全新的默认文件
    if (GetFileAttributesA(ini_path) == INVALID_FILE_ATTRIBUTES)
    {
        pk_config_create_default(ini_path);
    }
    else
    {
// 2. 如果文件存在，执行“增量补全” (Fix missing keys)
#define X(type, name, sec, key, val, desc) \
    CheckAndWriteDefault(ini_path, sec, key, val, desc);
#include "../inc/config_def.h"
#undef X
    }

// 3. 读取配置到内存
#define X(type, name, sec, key, val, desc) \
    g_pk_config.name = GetPrivateProfileIntA(sec, key, val, ini_path);
#include "../inc/config_def.h"
#undef X

    if (g_pk_config.item_stack_limit < 1)
        g_pk_config.item_stack_limit = 1;
    if (g_pk_config.item_stack_limit > 127)
        g_pk_config.item_stack_limit = 127;
}

void pk_config_create_default(const char *path)
{
    // ... (保持你之前的 create_default 代码不变) ...
    // 这个函数只在文件彻底不存在时调用一次
    FILE *f = fopen(path, "w");
    if (f)
    {
        fprintf(f, "; PlugK Configuration File\n; Generated by Config Tool\n\n");
        const char *current_section = "";
#define X(type, name, sec, key, val, desc) \
    if (strcmp(sec, current_section) != 0) \
    {                                      \
        fprintf(f, "\n[%s]\n", sec);       \
        current_section = sec;             \
    }                                      \
    fprintf(f, "; %s\n%s=%d\n", desc, key, val);
#include "../inc/config_def.h"
#undef X
        fclose(f);
    }
}
