#include <stdio.h>
#include <string.h>
#include "../inc/config.h"

// 全局配置实例
PK_CONFIG g_pk_config = {0};

// 定义宏映射，用于加载
#define TYPE_BOOL
#define TYPE_INT
#define TYPE_KEY

void pk_config_load(const char *optional_path)
{
    char ini_path[MAX_PATH];

    if (optional_path && strlen(optional_path) > 0)
    {
        strcpy_s(ini_path, MAX_PATH, optional_path);
    }
    else
    {
        // 默认 DLL 逻辑: 获取 DLL 自身路径
        char dll_path[MAX_PATH];
        HMODULE hModule = GetModuleHandleA("PlugK.dll");
        if (!hModule)
            hModule = GetModuleHandleA(NULL); // Fallback for EXE

        GetModuleFileNameA(hModule, dll_path, MAX_PATH);
        char *last_slash = strrchr(dll_path, '\\');
        if (last_slash)
            *(last_slash + 1) = '\0';
        snprintf(ini_path, MAX_PATH, "%sPlugK.ini", dll_path);
    }

    // 自动检查并创建默认文件
    if (GetFileAttributesA(ini_path) == INVALID_FILE_ATTRIBUTES)
    {
        pk_config_create_default(ini_path);
    }

// === X-Macro 自动生成读取逻辑 ===
// 所有类型在底层都是 int (BOOL也是int)，所以统一用 GetPrivateProfileIntA
#define X(type, name, sec, key, val, desc) \
    g_pk_config.name = GetPrivateProfileIntA(sec, key, val, ini_path);

#include "../inc/config_def.h"
#undef X
}

void pk_config_create_default(const char *path)
{
    FILE *f = fopen(path, "w");
    if (f)
    {
        fprintf(f, "; PlugK Configuration File\n");
        fprintf(f, "; Generated by Config Tool\n\n");

        // === X-Macro 自动生成写入逻辑 ===
        // 这里做一个简单的处理：按出现顺序写入，并附带注释
        // 为了美观，你可能需要手动调整 config_def.h 的顺序

        const char *current_section = "";

#define X(type, name, sec, key, val, desc) \
    if (strcmp(sec, current_section) != 0) \
    {                                      \
        fprintf(f, "\n[%s]\n", sec);       \
        current_section = sec;             \
    }                                      \
    fprintf(f, "; %s\n%s=%d\n", desc, key, val);

#include "../inc/config_def.h"
#undef X

        fclose(f);
    }
}